language: csharp
mono: none
dotnet: 2.1.4
script:
  - dotnet restore
  - dotnet build -c release -o ../bin
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      dotnet nuget push ./bin/Enbiso.Common.EventBus.RabbitMq.*.nupkg -s $NUGET_REGISTRY -k $NUGET_API_KEY;
      rm -f ./bin/Enbiso.Common.EventBus.RabbitMq.*.nupkg;
      dotnet nuget push ./bin/Enbiso.Common.EventBus.ServiceBus.*.nupkg -s $NUGET_REGISTRY -k $NUGET_API_KEY;
      rm -f ./bin/Enbiso.Common.EventBus.ServiceBus.*.nupkg;
      dotnet nuget push ./bin/Enbiso.Common.EventBus.*.nupkg -s $NUGET_REGISTRY -k $NUGET_API_KEY;
      rm -f ./bin/Enbiso.Common.EventBus.*.nupkg;
    fi