language: csharp
mono: none
dotnet: 2.1.4
script:
  - dotnet restore
  - dotnet build -c release -o ../bin
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      dotnet nuget push ./bin/*.nupkg -k $NUGET_API_KEY 
    fi